use_frameworks!

platform :ios, '9.0'

target 'LGHCommonUIModule_Example' do
  pod 'LGHCommonUIModule', :path => '../'
  
  pod 'LGHMacroAndCategoryModule', :path => '../../LGHMacroAndCategoryModule'

  target 'LGHCommonUIModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
