# Uncomment the next line to define a global platform for your project
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'Litter_item' do
  # 微信检测方案
  #  pod 'matrix-wechat', '~> 0.6.5'
  # Texture
  #  pod 'Texture', '~> 3.0.0'
  # 自动布局框架
  pod 'Masonry'       , '1.1.0'
  # ReactiveCocoa-objc
  pod 'ReactiveObjC'  , '3.1.1'
  # 内存泄漏检测框架(利用黑魔法)
  pod 'MLeaksFinder', '1.0.0'
  
  #Beelive
  pod "BeeHive", '1.1.1'

end

target 'Litter_itemTests' do

end

target 'Litter_itemUITests' do

end


