use_frameworks!

platform :ios, '9.0'

target 'LGHMacroAndCategoryModule_Example' do
  pod 'LGHMacroAndCategoryModule', :path => '../'

  target 'LGHMacroAndCategoryModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
