use_frameworks!

platform :ios, '9.0'

target 'LGHWebViewModule_Example' do
  pod 'LGHWebViewModule', :path => '../'

  target 'LGHWebViewModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
